/**
 * English console lines for remove-limit flow — line count per phase must match REMOVE_LIMIT_PHASES_ZH.
 */
export const REMOVE_LIMIT_PHASES_EN: { title: string; lines: string[] }[] = [
  {
    title: 'Control-plane link',
    lines: [
      '[Link] QMI + AT tunnel to cellular module; enumerate RNDIS/ECM on USB Composite; verify descriptors/bInterfaceClass.',
      '  • Identity: IMEI / IMSI / ICCID / EID (eUICC); soft SIM / remote provisioning vs carrier profile; SUPI/SUCI vs 5G-GUTI.',
      '  • NAS/EPS: PLMN, TAC, ECI; RSRP/RSRQ/SINR/CQI within thresholds; RRC Connected; TAU/RAU vs MME/AMF paging.',
      '  • Default PDN: APN vs subscription; dual-stack IPv4v6 vs HSS; DNS from PGW/SMF; PCO IE sanity.',
      '  • 5G PDU: S-NSSAI, DNN, SSC, URSP vs local FIB; IPv6 RA / DHCPv6-PD vs SMF prefix.',
      '  • MiFi: USB power/thermal; 2.4/5 GHz coexistence vs SAR throttling; DFS/radar channel events.',
      '  • Mgmt: TR-069 / OMA-DM / LwM2M idle; local removal path avoids stealing user-plane GBR; OMADM vs USIM OTA mutex.',
      '  • Time: NITZ/SIB; WiFi beacon slotting vs scheduling jitter; PTP/gPTP skew vs cellular clock.',
      '  • Probe: ICMP/TCP RTT baseline for post-removal delta; PMTUD and TCP MSS clamp vs core.',
      '  • RRC/AS: SRB/DRB map, PDCP SN, RLC AM/UM vs bearer; no RLC storm or HARQ NACK pile-up.',
      '  • NG-RAN: BWP, CORESET, search space, DCI vs band/numerology; SRS/CSI reporting cadence.',
      '  • Security: AKA/5G-AKA, RES*, KDF; integrity/cipher vs policy; no abnormal auth retries.',
      '  • Diag: QMI NAS/WDAN/WDS/WMS; diag vs QMI concurrency; USB bulk/NCM aggregation within OEM limits.',
      '  • Power: PSM/eDRX vs traffic; InactivityTimer vs T3324/T3412 without spurious detach.',
      '  • Voice: EPS FB / VoNR / SRVCC; IMS P-CSCF reachability; SIP register vs RTP port reservation.',
      '  • WiFi: SoftAP+STA; hostapd/cfg80211; bridge STP/RSTP vs cellular NAT domain.',
      '  • Stats: RRC duration, RLF, reestablish, reselection vs 24h baseline; ring buffer for diff.',
      '  • Probe: traceroute vs TCP handshake spread; ECN/CUBIC/BBR vs OEM CWND defaults.',
      '  • Hand-off: QMI txn IDs aligned; entering policy scan; release read-only diag handles.',
    ],
  },
  {
    title: 'Policy scan',
    lines: [
      '[Scan] Bearer QoS (QCI/5QI), TFT 5-tuple, SDF; DPI throttle fingerprint vs PCC/PCF rev; pull PCEF/TDF predefined rules.',
      '  • Hotspot: SNAT/DNAT, conntrack, hairpin, full-cone; DHCP vs CGNAT pool; SYN proxy vs nf_tcp timeouts.',
      '  • WiFi: WMM EDCA, 802.11k/v/r, BSS color; WPA3-SAE/PMF vs guest VLAN; MU-MIMO/OFDMA airtime fairness.',
      '  • Quota: local counters vs OCS online quota / OFCA offline window; “quota throttle” PCC bit; RG vs Service-ID.',
      '  • Voice/data: VoLTE/VoNR dedicated (QCI1/5QI2) vs default; SIP/RTP ALG; RTCP XR vs MOS gate.',
      '  • Security: IPSec summary, L2TP/GRE, zone firewall; DoT hijack scan; TLS1.3 ECH/ESNI vs DPI allowlist.',
      '  • DPI: HTTPS SNI / QUIC Initial classification; video/download/game to PCC App-ID; App-ID vs SDF precedence clash.',
      '  • Topology: bridge/routed dual-stack, IPv6-PD, NPTv6; ULA/GUA vs RFC6724 source selection.',
      '  • PCC: Charging-Rule-Name, precedence, Flow-Status, QoS-Information diff vs cache; predefined vs dynamic merge order.',
      '  • Charging: Gy/Ro, Gx/N7, N40 counters; quota consumption vs RG switch; FUI/FUA reauth window.',
      '  • Policing: color-blind/sensitive policer, shaper, HQoS parent/child; token bucket CBS/EBS vs PIR/CIR.',
      '  • Core: SPR/UDR policy set version; PCF subscription vs UE Policy/ANDSP ST expiry.',
      '  • Hotspot ACL: iptables/nft chain order vs zones; mangle/raw vs conntrack; symmetric ip6tables/nft.',
      '  • Multicast: IGMP/MLD snooping, querier, MLDv2; SSM/PIM-SM vs cellular multicast isolation.',
      '  • DPI mirror: ERSPAN/TAP sample rate; Zeek/Suricata rev; no bypass blackhole.',
      '  • HTTP/3: QUIC CID migration vs NAT rebinding; 0-RTT replay window; ALT-SVC vs H2 downgrade.',
      '  • Real-time: UDP short/long flow classes; ECN/DSCP remark vs radio L4S.',
      '  • OEM policy: smart-night throttle vs carrier PCC stacking; allowlist vs DPI cross-check.',
      '  • Output: policy delta vector + throttle confidence; mark Charging-Rule/QoS set for execution.',
    ],
  },
  {
    title: 'Execute removal',
    lines: [
      '[Exec] Push unlock: refresh local PCC cache; SMF/PGW (4G) or SMF/UPF (5G) bearer renegotiation; CCR/CCA vs Nchf/N40.',
      '  • Bearer: default MBR/GBR, Session-AMBR, UE-AMBR reset; strip rogue TFT and throttle DSCP/PHB; Reflective QoS/QFI mapping.',
      '  • User plane: keep GTP-U TEID / PFCP session; UPF QoS profile + gating refresh without PDU tear-down; N3/N9 F-TEID stable.',
      '  • Module: PDU Session Modify / PDP Context Modify (AT+QCFG); preserve IP/DNS; avoid TCP retransmit storm; RRC Reconfig with AS security.',
      '  • Hotspot: iptables/nft reload conntrack keepalive; UPnP/P2P/meeting 5-tuples; no stray event flush.',
      '  • Power: avoid forced C-DRX stretch; tweak DRX only in ACK window; block PSM hang.',
      '  • DR: alternate S-NSSAI/DNN probe if PGW/SMF down; PFCP heartbeat/association redundancy.',
      '  • Observe: N3/N6 latency/loss as side judge; TWAMP/STAMP vs UPF PM counters.',
      '  • N4 PFCP: Session Modification FAR/BAR/QER/URR deltas; Apply Action vs downlink split.',
      '  • Gy: CCR-U with USU, Reporting-Reason, QoS-Information; RG ordering in MSCC.',
      '  • Gx/N7: CC-Request-Type, Event-Trigger, Charging-Rule-Report vs PCF; no DIAMETER/NAS stall.',
      '  • RAN: NGAP E-RAB/PDU session modify vs QoS flow; DRB reconfig without app drop.',
      '  • Hotspot QoS: cake/fq_codel/htb offload; DSCP/skb mark/conntrack mark triple consistency.',
      '  • IPv6: SRv6 vs plain IPv6 path; hop limit/PMTU; temp vs stable addressing clash check.',
      '  • Security: IPsec CHILD_SA vs PFCP; TLS OCSP; TPM/TEE key handles sealed.',
      '  • Audit: removal txn id, rule hash vector, timestamps; optional BSS ticket id.',
      '  • Rollback: shadow PCC snapshot; two-phase commit dry-run then commit.',
      '  • Observe: short iperf3 vs passive span on critical 5-tuple; abort on anomaly.',
      '  • Hand-off: post “policy committed” to sync poller; release QMI lock; await core ACK.',
    ],
  },
  {
    title: 'Synchronization',
    lines: [
      '[Sync] Poll PGW-C/SMF and UPF PFCP/GTP ACK; Gy/Gx/N40 quota refresh; Nchf converged charging closes.',
      '  • Subscription: HSS/UDM profile vs PCF/PCRF rules; ST bump vs UDM Nudm_SDM/Nudr_DR read window.',
      '  • Charging: OCS online vs CDF batch vs OFCS offline; post-removal next billing gate; SCC in CDR.',
      '  • Radio: EN-DC MN/SN ordering; avoid SCG failure; NR CA/ENDC bandwidth policy; B1/B2 vs A2 mobility.',
      '  • Local: keep RRC; WiFi channel/beacon stable; prep DL/UL/jitter tri-test; ARP/ND reachability.',
      '  • Trace: removal session id, policy hash, QMI last error digest; CHR/CEM correlation keys.',
      '  • Core paths: S5/S8, S11, N4, N11, N40 health; DIAMETER realm routing.',
      '  • Close: policy sync window; final ACK; PFCP Session/Usage Report closure.',
      '  • UPF: buffering, DL Data Notification, End Marker ordering before QoS remark change.',
      '  • SMF: SM context version bump vs UPF; N4 Session Report vs Charging ID vs CHF.',
      '  • AMF/MME: reachability, paging, service request storms; N2/NGAP release/reestablish counts.',
      '  • PCRF/PCF: policy counter/session rule vs PCC install; Abort/NACK reason backoff.',
      '  • Charging close: Gy CCA FUI vs quota exhaustion; N40 ConsumptionReport vs ChargingData.',
      '  • Radio: RRC release w/ redirect/IRAT race vs policy refresh; SIB priority vs post-removal model.',
      '  • WiFi: CSA/DFS logs with cellular concurrency; OKC/802.11r roam vs TCP continuity.',
      '  • Observe: same 5-tuple throughput before/after; tail latency/retransmit gates; local summary for UI.',
      '  • Privacy: minimize PII in traces; redaction/retention; optional BSS upload with consent flag.',
      '  • Session end: drop audit buffer; persist removal result + policy rev for home history table.',
      '  • Done: core + UE state machines idle/connected steady; UI flag “ready to verify speed”.',
    ],
  },
]
